// Generated by scripts/build-pvp-bot-runtime.js; do not edit.
"use strict";
/**
 * 关卡数据接口定义
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_PCH_SINGLE_SELECTION_LIMIT = exports.CONVEYOR_STACK_DEPTH = exports.COLOR_HEX_LOCKED = exports.COLOR_NAMES = exports.COLOR_HEX = exports.BeanColor = void 0;
exports.validatePchSingleSelectionLimit = validatePchSingleSelectionLimit;
exports.validateConveyorCapacity = validateConveyorCapacity;
exports.validateHard = validateHard;
/**
 * 颜色 ID 映射。
 * 这些值与 `BootstrapBundle/Beans/bean-atlas-data.json` 中的 bNNN_* 帧名、关卡 JSON 数字一一对应。
 * 不要按历史英文色名推断颜色；以 COLOR_HEX / 豆豆图集实际帧为准。
 */
var BeanColor;
(function (BeanColor) {
    BeanColor[BeanColor["NONE"] = 0] = "NONE";
    BeanColor[BeanColor["ROSE"] = 1] = "ROSE";
    BeanColor[BeanColor["CYAN"] = 2] = "CYAN";
    BeanColor[BeanColor["GOLD"] = 3] = "GOLD";
    BeanColor[BeanColor["ORANGE"] = 4] = "ORANGE";
    BeanColor[BeanColor["PEACH"] = 5] = "PEACH";
    BeanColor[BeanColor["CREAM"] = 6] = "CREAM";
    BeanColor[BeanColor["INDIGO"] = 7] = "INDIGO";
    BeanColor[BeanColor["VIOLET"] = 8] = "VIOLET";
    BeanColor[BeanColor["LIME"] = 9] = "LIME";
    BeanColor[BeanColor["RED"] = 10] = "RED";
    BeanColor[BeanColor["GREEN"] = 11] = "GREEN";
    BeanColor[BeanColor["EMERALD"] = 12] = "EMERALD";
    BeanColor[BeanColor["SKY_BLUE"] = 13] = "SKY_BLUE";
    BeanColor[BeanColor["PINK"] = 14] = "PINK";
    BeanColor[BeanColor["LAVENDER"] = 15] = "LAVENDER";
    BeanColor[BeanColor["BROWN"] = 16] = "BROWN";
    BeanColor[BeanColor["MAROON"] = 17] = "MAROON";
    BeanColor[BeanColor["NAVY"] = 18] = "NAVY";
    BeanColor[BeanColor["CHARCOAL"] = 19] = "CHARCOAL";
    BeanColor[BeanColor["IVORY"] = 20] = "IVORY";
})(BeanColor || (exports.BeanColor = BeanColor = {}));
/** 颜色 ID 到主视觉色值映射（取自 bNNN_2 正常豆子贴图主色） */
exports.COLOR_HEX = {
    1: '#ED5090',
    2: '#4EEAEA',
    3: '#F8C811',
    4: '#FE8B10',
    5: '#F4BD9E',
    6: '#EBDEA6',
    7: '#4A4DCF',
    8: '#7221BC',
    9: '#9FCE21',
    10: '#EA281A',
    11: '#37A92D',
    12: '#207955',
    13: '#20A8DC',
    14: '#EEB2BC',
    15: '#C4BED9',
    16: '#974714',
    17: '#782F3C',
    18: '#36387E',
    19: '#373737',
    20: '#F2EDE4',
};
/** 设计/工具展示用中文色名 */
exports.COLOR_NAMES = {
    1: '玫红',
    2: '亮青',
    3: '金',
    4: '橙',
    5: '桃',
    6: '浅黄',
    7: '靛蓝',
    8: '紫',
    9: '绿',
    10: '红',
    11: '青绿',
    12: '翠绿',
    13: '天蓝',
    14: '粉',
    15: '浅紫',
    16: '棕',
    17: '酒红',
    18: '藏青',
    19: '深灰',
    20: '米白',
};
/** 简化锁定态色值。实际锁定豆子优先使用 bNNN_1 贴图。 */
exports.COLOR_HEX_LOCKED = {
    1: '#A82860',
    2: '#35A09A',
    3: '#BC7A02',
    4: '#B65600',
    5: '#B68574',
    6: '#ACA172',
    7: '#3235A0',
    8: '#51148A',
    9: '#6C9606',
    10: '#AC1E11',
    11: '#267921',
    12: '#12543A',
    13: '#0F72A2',
    14: '#AA7F88',
    15: '#847F96',
    16: '#662E0A',
    17: '#5A1C27',
    18: '#212259',
    19: '#242424',
    20: '#AFA99F',
};
/** 新版传送带每个载具可堆叠的豆豆数量。 */
exports.CONVEYOR_STACK_DEPTH = 3;
/** 新版传送带单次从棋盘选取豆豆的默认数量上限。 */
exports.DEFAULT_PCH_SINGLE_SELECTION_LIMIT = 12;
/** 校验关卡配置的单次选取数量；未配置时沿用默认值。 */
function validatePchSingleSelectionLimit(value, label = 'level data') {
    if (value === undefined || value === null)
        return exports.DEFAULT_PCH_SINGLE_SELECTION_LIMIT;
    if (typeof value !== 'number' || !Number.isInteger(value) || value <= 0) {
        throw new Error(`[SingleSelectionLimit] ${label}.singleSelectionLimit must be a positive integer: ${value}`);
    }
    return value;
}
/** 校验关卡配置的新版传送带容量（单位：豆豆颗数）。 */
function validateConveyorCapacity(value, label = 'level data') {
    if (typeof value !== 'number' || !Number.isInteger(value) || value <= 0) {
        throw new Error(`[ConveyorCapacity] ${label}.conveyorCapacity must be a positive integer: ${value}`);
    }
    return value;
}
/** 校验关卡入场难度标记；缺失或非法值必须显性失败。 */
function validateHard(value, label = 'level data') {
    if (value !== 0 && value !== 1) {
        throw new Error(`[Hard] ${label}.Hard must be 0 or 1: ${value}`);
    }
    return value;
}
