// Generated by scripts/build-pvp-bot-runtime.js; do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RAINBOW_CONVEYOR_CORNER_RADIUS = exports.RAINBOW_CONVEYOR_EXIT_POINT_INDEX = exports.RAINBOW_CONVEYOR_PATHS = void 0;
exports.createRoundedConveyorPath = createRoundedConveyorPath;
exports.sampleRoundedConveyorPath = sampleRoundedConveyorPath;
exports.conveyorExitProgress = conveyorExitProgress;
exports.RAINBOW_CONVEYOR_PATHS = {
    2: [[-219, -99], [390, -96], [390, 104.2], [152, 104.2], [-396, 104.2], [-390, -92]],
    3: [[-327, -159], [447, -162], [447, 161], [263, 161], [264, 50],
        [163, 50], [-279, 47], [-279, 166.3], [-452, 166.3], [-452, -159]],
};
exports.RAINBOW_CONVEYOR_EXIT_POINT_INDEX = { 2: 3, 3: 5 };
const RAINBOW_CONVEYOR_ROUNDED_CORNERS = {
    2: new Set([1, 2, 4, 5]),
    3: new Set([1, 2, 3, 4, 6, 7, 8, 9]),
};
exports.RAINBOW_CONVEYOR_CORNER_RADIUS = 40;
const PATH_EPSILON = 1e-6;
function pointDistance(a, b) {
    return Math.hypot(b.x - a.x, b.y - a.y);
}
function createRoundedCorner(points, index, radius, rounded) {
    const current = points[index];
    if (!rounded)
        return { entry: current, exit: current, arc: null };
    const previous = points[(index - 1 + points.length) % points.length];
    const next = points[(index + 1) % points.length];
    const incomingLength = pointDistance(previous, current);
    const outgoingLength = pointDistance(current, next);
    if (incomingLength <= PATH_EPSILON || outgoingLength <= PATH_EPSILON) {
        return { entry: current, exit: current, arc: null };
    }
    const incomingX = (current.x - previous.x) / incomingLength;
    const incomingY = (current.y - previous.y) / incomingLength;
    const outgoingX = (next.x - current.x) / outgoingLength;
    const outgoingY = (next.y - current.y) / outgoingLength;
    const dot = Math.max(-1, Math.min(1, incomingX * outgoingX + incomingY * outgoingY));
    const turnAngle = Math.acos(dot);
    const cross = incomingX * outgoingY - incomingY * outgoingX;
    if (Math.abs(cross) <= PATH_EPSILON || turnAngle <= PATH_EPSILON || turnAngle >= Math.PI - PATH_EPSILON) {
        return { entry: current, exit: current, arc: null };
    }
    const tangentScale = Math.tan(turnAngle / 2);
    const trim = Math.min(radius * tangentScale, incomingLength * 0.45, outgoingLength * 0.45);
    if (trim <= PATH_EPSILON || tangentScale <= PATH_EPSILON) {
        return { entry: current, exit: current, arc: null };
    }
    const effectiveRadius = trim / tangentScale;
    const entry = { x: current.x - incomingX * trim, y: current.y - incomingY * trim };
    const exit = { x: current.x + outgoingX * trim, y: current.y + outgoingY * trim };
    const turnSign = Math.sign(cross);
    const center = {
        x: entry.x - incomingY * turnSign * effectiveRadius,
        y: entry.y + incomingX * turnSign * effectiveRadius,
    };
    const startAngle = Math.atan2(entry.y - center.y, entry.x - center.x);
    const endAngle = Math.atan2(exit.y - center.y, exit.x - center.x);
    let sweepAngle = endAngle - startAngle;
    if (turnSign > 0 && sweepAngle < 0)
        sweepAngle += Math.PI * 2;
    if (turnSign < 0 && sweepAngle > 0)
        sweepAngle -= Math.PI * 2;
    return {
        entry,
        exit,
        arc: {
            kind: 'arc',
            length: Math.abs(sweepAngle) * effectiveRadius,
            center,
            radius: effectiveRadius,
            startAngle,
            sweepAngle,
        },
    };
}
function createRoundedConveyorPath(tableType = 2, scale = 1) {
    if (!Number.isFinite(scale) || scale <= 0)
        throw new Error('invalid conveyor path scale');
    const points = exports.RAINBOW_CONVEYOR_PATHS[tableType]
        .map(([x, y]) => ({ x: x * scale, y: y * scale }));
    const roundedCorners = RAINBOW_CONVEYOR_ROUNDED_CORNERS[tableType];
    const corners = points.map((_, index) => createRoundedCorner(points, index, exports.RAINBOW_CONVEYOR_CORNER_RADIUS * scale, roundedCorners.has(index)));
    const segments = [];
    const waypointDistances = new Array(points.length).fill(0);
    let totalLength = 0;
    for (let index = 0; index < points.length; index += 1) {
        const nextIndex = (index + 1) % points.length;
        const start = corners[index].exit;
        const end = corners[nextIndex].entry;
        const lineLength = pointDistance(start, end);
        if (lineLength > PATH_EPSILON) {
            segments.push({
                kind: 'line',
                startDistance: totalLength,
                length: lineLength,
                start,
                end,
                angle: Math.atan2(end.y - start.y, end.x - start.x),
            });
            totalLength += lineLength;
        }
        const cornerArc = corners[nextIndex].arc;
        if (nextIndex !== 0)
            waypointDistances[nextIndex] = totalLength + ((cornerArc === null || cornerArc === void 0 ? void 0 : cornerArc.length) || 0) / 2;
        if (cornerArc && cornerArc.length > PATH_EPSILON) {
            segments.push({ ...cornerArc, startDistance: totalLength });
            totalLength += cornerArc.length;
        }
    }
    if (totalLength <= PATH_EPSILON || !segments.length)
        throw new Error(`invalid conveyor path for table type ${tableType}`);
    return { segments, totalLength, waypointDistances };
}
function sampleRoundedConveyorPath(path, progress, outPosition) {
    const wrappedProgress = ((progress % 1) + 1) % 1;
    const distance = wrappedProgress * path.totalLength;
    for (let index = 0; index < path.segments.length; index += 1) {
        const segment = path.segments[index];
        const endDistance = segment.startDistance + segment.length;
        if (distance > endDistance && index < path.segments.length - 1)
            continue;
        const ratio = Math.max(0, Math.min(1, (distance - segment.startDistance) / segment.length));
        if (segment.kind === 'line') {
            outPosition.x = segment.start.x + (segment.end.x - segment.start.x) * ratio;
            outPosition.y = segment.start.y + (segment.end.y - segment.start.y) * ratio;
            return segment.angle * 180 / Math.PI;
        }
        const angle = segment.startAngle + segment.sweepAngle * ratio;
        outPosition.x = segment.center.x + Math.cos(angle) * segment.radius;
        outPosition.y = segment.center.y + Math.sin(angle) * segment.radius;
        const direction = Math.sign(segment.sweepAngle);
        return Math.atan2(Math.cos(angle) * direction, -Math.sin(angle) * direction) * 180 / Math.PI;
    }
    throw new Error('failed to sample conveyor path');
}
function conveyorExitProgress(tableType = 2) {
    const path = createRoundedConveyorPath(tableType);
    return path.waypointDistances[exports.RAINBOW_CONVEYOR_EXIT_POINT_INDEX[tableType]] / path.totalLength;
}
