// Generated by scripts/build-pvp-bot-runtime.js; do not edit.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PvpHumanReplay = exports.HUMAN_REPLAY_VERIFICATION = exports.HUMAN_REPLAY_PROTOCOL = void 0;
exports.replayHumanEvents = replayHumanEvents;
const BoardModel_1 = require("./BoardModel");
const PchConveyorRules_1 = require("./PchConveyorRules");
const PchConveyorGeometry_1 = require("./PchConveyorGeometry");
const PvpBotReplay_1 = require("./PvpBotReplay");
exports.HUMAN_REPLAY_PROTOCOL = 'pch-events-v1';
exports.HUMAN_REPLAY_VERIFICATION = 'replay-verified-v1';
class PvpHumanReplay {
    constructor(level) {
        this.level = level;
        this.boardTimeline = [];
        this.actions = [];
        this.pendingReady = [];
        this.travel = 0;
        this.speed = 1;
        this.lastTime = 0;
        this.firstTap = -1;
        this.completedAt = -1;
        this.deadlockedAt = -1;
        this.simulatedMs = 0;
        this.initialized = false;
        this.autoSpeed = false;
        this.exit = (0, PchConveyorGeometry_1.conveyorExitProgress)();
        this.locked = 0;
        this.board = new BoardModel_1.BoardModel(level);
        this.rules = new PchConveyorRules_1.PchConveyorRules(this.board, level.conveyorCapacity, level.singleSelectionLimit);
        const cells = [];
        let total = 0;
        for (let row = 0; row < this.board.height; row++)
            for (let col = 0; col < this.board.width; col++) {
                if (this.board.correctColors[row][col])
                    total++;
                if (this.board.locked[row][col])
                    cells.push({ row, col, colorId: this.board.correctColors[row][col] });
            }
        if (!total || total > 4096)
            throw new Error('invalid replay level');
        this.total = total;
        this.addCells(0, cells);
    }
    get progress() { return this.locked / this.total; }
    addCells(time, cells) {
        if (!cells.length)
            return;
        this.locked += cells.length;
        const previous = this.boardTimeline[this.boardTimeline.length - 1];
        if (previous && previous.elapsedMs > 0 && Math.floor(previous.elapsedMs / 2000) === Math.floor(time / 2000)) {
            previous.elapsedMs = time;
            previous.addedCells.push(...cells);
        }
        else
            this.boardTimeline.push({ elapsedMs: time, addedCells: cells });
        if (this.locked === this.total && this.completedAt < 0)
            this.completedAt = time;
    }
    apply(event) {
        if (!Array.isArray(event) || event.some(value => !Number.isFinite(value)))
            throw new Error('invalid replay event');
        const [time, kind, a, b, c, d] = event;
        if (!Number.isInteger(time) || time < this.lastTime || time > 600000)
            throw new Error('invalid replay time');
        const arity = [3, 3, 6, 2, 3][kind];
        if (event.length !== arity)
            throw new Error('unknown replay command');
        this.lastTime = time;
        if (!this.initialized && kind !== 0)
            throw new Error('missing replay initialization');
        if (kind === 0 || kind === 4) {
            if ([1, 2, 3].indexOf(a) < 0 || (kind === 0 && this.initialized))
                throw new Error('invalid replay speed');
            this.initialized = true;
            this.speed = a;
        }
        else if (kind === 2) {
            if (this.completedAt >= 0 || this.rules.isBufferDeadlocked())
                throw new Error('action after terminal');
            if (this.firstTap >= 0 && time > this.firstTap + this.level.timeLimit * 1000 + 1000)
                throw new Error('action after timeout');
            if (![a, b, c, d].every(Number.isInteger))
                throw new Error('invalid replay tap');
            const block = this.rules.selectBoard(a, b);
            if (!block || block.colorId !== c)
                throw new Error('illegal replay selection');
            const moved = this.rules.storeBlock(block, 0).moved;
            if (!moved || moved !== d)
                throw new Error('illegal replay move count');
            if (this.firstTap < 0)
                this.firstTap = time;
            for (let index = 0; index < moved; index++)
                this.pendingReady.push(time + 160 + index * 12);
            this.pendingReady.sort((x, y) => x - y);
            this.actions.push({ seq: this.actions.length + 1, elapsedMs: time, row: a, col: b, colorId: c, moved: d });
        }
        else if (kind === 3) {
            // Animation callbacks may be one frame early relative to rounded wall time.
            if (!this.pendingReady.length || time + 34 < this.pendingReady[0])
                throw new Error('premature replay arrival');
            this.pendingReady.shift();
            if (this.rules.markQueuedBeansReady(1) !== 1)
                throw new Error('invalid replay arrival');
            let nearest = 0;
            let distance = Infinity;
            for (let index = 0; index < this.rules.carrierCount; index++) {
                const progress = ((index + this.travel) / this.rules.carrierCount) % 1;
                const delta = Math.min(progress, 1 - progress);
                if (delta < distance) {
                    nearest = index;
                    distance = delta;
                }
            }
            if (distance <= 0.032)
                this.rules.transferReadyBeansToCarrier(nearest);
        }
        else if (kind === 1) {
            if (a < this.travel)
                throw new Error('reversed replay belt');
            if (this.rules.conveyorSpeedMultiplier === 5)
                this.autoSpeed = true;
            this.simulatedMs += (a - this.travel) * 250 / (this.autoSpeed ? 5 : this.speed);
            if (this.simulatedMs > time + 250)
                throw new Error('accelerated replay clock');
            const before = this.travel;
            this.travel = a;
            const count = this.rules.carrierCount;
            const crossed = (index, fraction) => Math.floor((index + a) / count - fraction)
                > Math.floor((index + before) / count - fraction);
            const cells = [];
            for (let index = 0; index < count; index++) {
                if (crossed(index, 1 - 0.2 / count) || crossed(index, 0))
                    this.rules.transferReadyBeansToCarrier(index);
                if (crossed(index, this.exit)) {
                    const placed = this.rules.autoPlaceAvailableLayers(index);
                    placed.boardCells.forEach((cell, n) => cells.push({ ...cell, colorId: placed.colorIds[n] }));
                }
            }
            this.addCells(time, cells);
            if (this.rules.isBufferDeadlocked() && this.deadlockedAt < 0)
                this.deadlockedAt = time;
        }
    }
    finish(terminalType, time) {
        if (!Number.isInteger(time) || time < this.lastTime || time > 600000)
            throw new Error('invalid terminal time');
        if (terminalType === 'PASS' && (this.completedAt < 0 || time - this.completedAt > 10000))
            throw new Error('unverified pass');
        if (terminalType === 'PASS' && this.firstTap >= 0 && this.completedAt > this.firstTap + this.level.timeLimit * 1000 + 1000)
            throw new Error('pass after timeout');
        if (terminalType === 'SURVIVED_OPPONENT_DEATH' && this.firstTap >= 0 && time > this.firstTap + this.level.timeLimit * 1000 + 1000)
            throw new Error('survival after timeout');
        if (terminalType === 'DEAD_CONVEYOR_FULL' && (!this.rules.isBufferDeadlocked() || this.deadlockedAt < 0
            || time - this.deadlockedAt > 1000))
            throw new Error('unverified deadlock');
        if (terminalType === 'DEAD_TIMEOUT' && (this.firstTap < 0 || time < this.firstTap + this.level.timeLimit * 1000 - 1000
            || this.completedAt >= 0))
            throw new Error('unverified timeout');
        if (['PASS', 'DEAD_CONVEYOR_FULL', 'DEAD_TIMEOUT', 'FORFEIT', 'SURVIVED_OPPONENT_DEATH'].indexOf(terminalType) < 0)
            throw new Error('invalid terminal');
        let locked = 0;
        const progressTimeline = this.boardTimeline.map(point => {
            locked += point.addedCells.length;
            return { elapsedMs: point.elapsedMs, progress: locked / this.total };
        });
        if (!progressTimeline.length || progressTimeline[0].elapsedMs > 0)
            progressTimeline.unshift({ elapsedMs: 0, progress: 0 });
        if (progressTimeline[progressTimeline.length - 1].elapsedMs !== time)
            progressTimeline.push({ elapsedMs: time, progress: this.progress });
        return { progress: this.progress, boardTimeline: this.boardTimeline, progressTimeline,
            completeRun: ['PASS', 'DEAD_CONVEYOR_FULL', 'DEAD_TIMEOUT'].indexOf(terminalType) >= 0 };
    }
}
exports.PvpHumanReplay = PvpHumanReplay;
function replayHumanEvents(level, envelope) {
    if ((envelope === null || envelope === void 0 ? void 0 : envelope.protocol) !== exports.HUMAN_REPLAY_PROTOCOL || envelope.levelHash !== (0, PvpBotReplay_1.pixelLevelHash)(level))
        throw new Error('replay version mismatch');
    if (!Array.isArray(envelope.events) || !envelope.events.length || envelope.events.length > 75000
        || JSON.stringify(envelope).length > 2500000)
        throw new Error('invalid replay envelope');
    const replay = new PvpHumanReplay(level);
    for (const event of envelope.events)
        replay.apply(event);
    return replay;
}
