// Generated by scripts/prepare-profile-assets.js
module.exports = {
  "1001": {
    "kind": "avatar",
    "asset": "1001.28f25bebd850.png"
  },
  "1002": {
    "kind": "avatar",
    "asset": "1002.6abe2f7d6408.png"
  },
  "1003": {
    "kind": "avatar",
    "asset": "1003.77957fcf0314.png"
  },
  "1004": {
    "kind": "avatar",
    "asset": "1004.1205a7823de8.png"
  },
  "1005": {
    "kind": "avatar",
    "asset": "1005.e8511bfcea47.png"
  },
  "1009": {
    "kind": "avatar",
    "asset": "1009.322e8d284485.png"
  },
  "1010": {
    "kind": "avatar",
    "asset": "1010.7993d4487841.png"
  },
  "1011": {
    "kind": "avatar",
    "asset": "1011.a0c026d48006.png"
  },
  "1012": {
    "kind": "avatar",
    "asset": "1012.150bde008f07.png"
  },
  "1029": {
    "kind": "avatar",
    "asset": "1029.0b34025e61a3.png"
  },
  "1030": {
    "kind": "avatar",
    "asset": "1030.6566fb4b1619.png"
  },
  "1031": {
    "kind": "avatar",
    "asset": "1031.1f941dafe970.png"
  },
  "2001": {
    "kind": "frame",
    "asset": "2001.f5d1184f47b5.png"
  },
  "2003": {
    "kind": "frame",
    "asset": "2003.a41407e1ce8d.png"
  },
  "2004": {
    "kind": "frame",
    "asset": "2004.7dadf00e94f5.png"
  },
  "2005": {
    "kind": "frame",
    "asset": "2005.cf7074844ffe.png"
  },
  "2006": {
    "kind": "frame",
    "asset": "2006.eec00f1f9748.png"
  },
  "2007": {
    "kind": "frame",
    "asset": "2007.354687ba3794.png"
  },
  "2008": {
    "kind": "frame",
    "asset": "2008.eeb5e1764d6b.png"
  },
  "2009": {
    "kind": "frame",
    "asset": "2009.ab2af05782aa.png"
  },
  "2010": {
    "kind": "frame",
    "asset": "2010.296ab0627cab.png"
  },
  "2011": {
    "kind": "frame",
    "asset": "2011.5f6a1af76a4b.png"
  },
  "2012": {
    "kind": "frame",
    "asset": "2012.59ef648851c4.png"
  },
  "2013": {
    "kind": "frame",
    "asset": "2013.a0e9df69264f.png"
  },
  "2014": {
    "kind": "frame",
    "asset": "2014.d8e1eca2aec8.png"
  }
};
