// Generated by scripts/prepare-profile-assets.js
module.exports = {
  "2001": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2003": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2004": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2005": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2006": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2007": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2008": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2009": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2010": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2011": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2012": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2013": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  },
  "2014": {
    "width": 256,
    "height": 256,
    "bounds": [
      49,
      49,
      207,
      207
    ]
  }
};
