const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { PNG } = require('pngjs');
const ts = require('typescript');

require('ts-node').register({
  transpileOnly: true,
  project: path.join(__dirname, '..', 'scripts', 'tsconfig.pvp-tests.json'),
  compilerOptions: { rootDir: path.join(__dirname, '..') },
});

const geometry = require('../assets/Scripts/Core/PchConveyorGeometry.ts');

function close(actual, expected, epsilon, message) {
  assert.ok(Math.abs(actual - expected) <= epsilon, `${message}: expected ${expected}, got ${actual}`);
}

function shortestAngleDelta(a, b) {
  return Math.abs((((a - b) % 360) + 540) % 360 - 180);
}

for (const tableType of [2, 3]) {
  const route = geometry.createRoundedConveyorPath(tableType);
  const scaledRoute = geometry.createRoundedConveyorPath(tableType, 0.6);
  assert.ok(route.totalLength > 0, `table ${tableType} route must have positive length`);
  assert.ok(route.segments.some(segment => segment.kind === 'arc'), `table ${tableType} must contain arcs`);
  close(scaledRoute.totalLength, route.totalLength * 0.6, 1e-8, `table ${tableType} scaled length`);

  const start = { x: 0, y: 0 };
  geometry.sampleRoundedConveyorPath(route, 0, start);
  close(start.x, geometry.RAINBOW_CONVEYOR_PATHS[tableType][0][0], 1e-8, `table ${tableType} entrance x`);
  close(start.y, geometry.RAINBOW_CONVEYOR_PATHS[tableType][0][1], 1e-8, `table ${tableType} entrance y`);

  const exitIndex = geometry.RAINBOW_CONVEYOR_EXIT_POINT_INDEX[tableType];
  const exitProgress = geometry.conveyorExitProgress(tableType);
  const exit = { x: 0, y: 0 };
  geometry.sampleRoundedConveyorPath(route, exitProgress, exit);
  close(exit.x, geometry.RAINBOW_CONVEYOR_PATHS[tableType][exitIndex][0], 1e-8, `table ${tableType} exit x`);
  close(exit.y, geometry.RAINBOW_CONVEYOR_PATHS[tableType][exitIndex][1], 1e-8, `table ${tableType} exit y`);

  let previousAngle = geometry.sampleRoundedConveyorPath(route, 0, { x: 0, y: 0 });
  let largestAngleStep = 0;
  for (let step = 1; step <= 8000; step += 1) {
    const angle = geometry.sampleRoundedConveyorPath(route, step / 8000, { x: 0, y: 0 });
    largestAngleStep = Math.max(largestAngleStep, shortestAngleDelta(angle, previousAngle));
    previousAngle = angle;
  }
  assert.ok(largestAngleStep < 10, `table ${tableType} still has a hard direction jump: ${largestAngleStep}`);
}

const normalRoute = geometry.createRoundedConveyorPath(2);
const firstCornerProgress = normalRoute.waypointDistances[1] / normalRoute.totalLength;
const firstCorner = { x: 0, y: 0 };
const firstCornerAngle = geometry.sampleRoundedConveyorPath(normalRoute, firstCornerProgress, firstCorner);
assert.ok(firstCorner.x < 390 && firstCorner.y > -96, 'first rounded corner must cut inside the old hard vertex');
assert.ok(firstCornerAngle > 30 && firstCornerAngle < 60, `first rounded corner tangent must be diagonal, got ${firstCornerAngle}`);

const arrowPath = path.join(
  __dirname,
  '..',
  'assets',
  'BootstrapBundle',
  'GameUI',
  'RainbowConveyor',
  'Atlases',
  'ConveyorSmall',
  'conveyor_0.png',
);
const arrow = PNG.sync.read(fs.readFileSync(arrowPath));
assert.deepEqual([arrow.width, arrow.height], [26, 43], 'moving arrow native size must remain unchanged');
let visiblePixels = 0;
let maxAlpha = 0;
for (let offset = 0; offset < arrow.data.length; offset += 4) {
  const alpha = arrow.data[offset + 3];
  if (!alpha) continue;
  visiblePixels += 1;
  maxAlpha = Math.max(maxAlpha, alpha);
  assert.deepEqual(
    [arrow.data[offset], arrow.data[offset + 1], arrow.data[offset + 2]],
    [198, 204, 226],
    'moving arrow must use one flat pale lavender-blue color',
  );
}
assert.ok(visiblePixels > 0, 'moving arrow alpha mask must not be empty');
assert.equal(maxAlpha, 158, 'moving arrow opacity must stay at 62 percent');

const controllerSource = fs.readFileSync(
  path.join(__dirname, '..', 'assets', 'Scripts', 'Core', 'PchConveyorGameplayController.ts'),
  'utf8',
);
assert.match(controllerSource, /const PCH_DIRECTION_SCALE = 0\.86;/, 'moving arrow scale contract');
assert.match(controllerSource, /direction\.setScale\(PCH_DIRECTION_SCALE, PCH_DIRECTION_SCALE, 1\);/, 'moving arrow scale application');
assert.match(controllerSource, /direction\.active = stack\.length === 0;/, 'occupied carriers must still hide the arrow');
assert.match(controllerSource, /const BELT_STEP_SECONDS = 0\.25;/, 'belt speed timing must remain unchanged');

const geometrySource = fs.readFileSync(
  path.join(__dirname, '..', 'assets', 'Scripts', 'Core', 'PchConveyorGeometry.ts'),
  'utf8',
);
const expectedPvpGeometry = '// Generated by scripts/build-pvp-bot-runtime.js; do not edit.\n' + ts.transpileModule(
  geometrySource,
  { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2019 }, reportDiagnostics: true },
).outputText;
const actualPvpGeometry = fs.readFileSync(
  path.join(__dirname, '..', 'cloudfunctions', 'pvpService', 'bot-runtime', 'PchConveyorGeometry.js'),
  'utf8',
);
assert.equal(actualPvpGeometry, expectedPvpGeometry, 'PVP geometry runtime must match the client rounded route');

console.log('pch conveyor rounded path checks passed');
