// Generated by scripts/build-coop-runtime.js.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COOP_ROUTE_REASON = exports.COOP_MAX_ELAPSED_MS = exports.COOP_LEGACY_RULES_VERSION = exports.COOP_RULES_VERSION = void 0;
exports.coopRegionGrid = coopRegionGrid;
exports.coopLevelHash = coopLevelHash;
exports.coopHalfLevel = coopHalfLevel;
const PvpBotReplay_1 = require("./PvpBotReplay");
exports.COOP_RULES_VERSION = 'coop-pch-v4';
exports.COOP_LEGACY_RULES_VERSION = 'coop-pch-v3';
exports.COOP_MAX_ELAPSED_MS = 365 * 86400000;
exports.COOP_ROUTE_REASON = 'pixel-coop';
function coopRegionGrid(full, role) {
    const owner = role === 'creator' ? 1 : 2;
    return full.correctColorArr.map((row, r) => row.map((color, c) => (full.coopRegions ? full.coopRegions[r][c] === owner : (c < 32) === (owner === 1)) ? color : 0));
}
function coopLevelHash(full) {
    return (0, PvpBotReplay_1.pixelLevelHash)(full) + (full.coopRegions ? '-' + (0, PvpBotReplay_1.pixelLevelHash)({ ...full,
        correctColorArr: full.coopRegions, initRandomColorArr: full.coopRegions }) : '');
}
function coopHalfLevel(full, role) {
    var _a, _b, _c;
    if (full.boardWidth !== 64 || full.boardHeight !== 56 || !['creator', 'collaborator'].includes(role))
        throw new Error('合作关卡分区不匹配');
    if (full.coopRegions) {
        const counts = [0, 0, 0], balances = [new Map(), new Map(), new Map()];
        if (full.coopRegions.length !== full.boardHeight)
            throw new Error('合作区域高度不匹配');
        for (let r = 0; r < full.boardHeight; r++) {
            if (((_a = full.coopRegions[r]) === null || _a === void 0 ? void 0 : _a.length) !== full.boardWidth || ((_b = full.correctColorArr[r]) === null || _b === void 0 ? void 0 : _b.length) !== full.boardWidth
                || ((_c = full.initRandomColorArr[r]) === null || _c === void 0 ? void 0 : _c.length) !== full.boardWidth)
                throw new Error('合作区域宽度不匹配');
            for (let c = 0; c < full.boardWidth; c++) {
                const color = full.correctColorArr[r][c], current = full.initRandomColorArr[r][c], owner = full.coopRegions[r][c];
                if (color ? owner !== 1 && owner !== 2 : owner !== 0 || current !== 0)
                    throw new Error('合作区域归属无效');
                if (color) {
                    if (!Number.isInteger(color) || color < 1 || color > 20 || !Number.isInteger(current) || current < 1 || current > 20)
                        throw new Error('合作颜色无效');
                    counts[owner]++;
                    const balance = balances[owner];
                    balance.set(color, (balance.get(color) || 0) + 1);
                    balance.set(current, (balance.get(current) || 0) - 1);
                }
            }
        }
        if (!counts[1] || !counts[2] || balances.some(balance => Array.from(balance.values()).some(value => value !== 0)))
            throw new Error('合作区域颜色数量不守恒');
        const owner = role === 'creator' ? 1 : 2;
        return { ...full, timeLimit: exports.COOP_MAX_ELAPSED_MS / 1000, autoConveyorFinishSpeed: false,
            correctColorArr: coopRegionGrid(full, role),
            initRandomColorArr: full.initRandomColorArr.map((row, r) => row.map((color, c) => full.coopRegions[r][c] === owner ? color : 0)) };
    }
    const start = role === 'creator' ? 0 : 32;
    return { ...full, boardWidth: 32, timeLimit: exports.COOP_MAX_ELAPSED_MS / 1000, autoConveyorFinishSpeed: false,
        correctColorArr: full.correctColorArr.map(row => row.slice(start, start + 32)),
        initRandomColorArr: full.initRandomColorArr.map(row => row.slice(start, start + 32)) };
}
