// Generated by scripts/build-coop-runtime.js.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.COOP_ROUTE_REASON = exports.COOP_MAX_ELAPSED_MS = exports.COOP_RULES_VERSION = void 0;
exports.coopHalfLevel = coopHalfLevel;
exports.COOP_RULES_VERSION = 'coop-pch-v3';
exports.COOP_MAX_ELAPSED_MS = 365 * 86400000;
exports.COOP_ROUTE_REASON = 'pixel-coop';
function coopHalfLevel(full, role) {
    if (full.boardWidth !== 64 || full.boardHeight !== 56 || !['creator', 'collaborator'].includes(role))
        throw new Error('合作关卡分区不匹配');
    const start = role === 'creator' ? 0 : 32;
    return { ...full, boardWidth: 32, timeLimit: exports.COOP_MAX_ELAPSED_MS / 1000, autoConveyorFinishSpeed: false,
        correctColorArr: full.correctColorArr.map(row => row.slice(start, start + 32)),
        initRandomColorArr: full.initRandomColorArr.map(row => row.slice(start, start + 32)) };
}
