import {
    BoardViewportController,
    Bundle,
    Color,
    DEFAULT_CELL_GAP,
    DEFAULT_CELL_SIZE,
    Label,
    Node,
    NodePool,
    SpriteFrame,
    Tween,
    Vec2,
    Vec3,
} from './GameCtrlShared';

export function initializeGameCtrlState(runtime: any): void {
    if (runtime._runtimeStateInitialized) {
        return;
    }
    runtime._runtimeStateInitialized = true;

    Object.assign(runtime, {
        isGameEnd: false,
        boardModel: null,
        slotModel: null,
        levelData: null,
        boardNode: null,
        boardSlotsNode: null,
        _boardSlotBatchRenderer: null,
        _boardSlotBatchRenderers: [],
        boardSlotBgNodes: [],
        boardGroup: null,
        cellNodes: [],
        slotNodes: [],
        slotMarkerNodes: [],
        slotAreaNode: null,
        _slotAreaSceneBaseX: 0,
        _slotAreaSceneBasePanelBottomY: null as number | null,
        _slotAreaScenePanelLocalY: 0,
        _slotAreaScenePanelWidth: 0,
        _slotAreaSceneRowSpacing: null as number | null,
        _slotAreaSceneLockMaskLayout: null as any,
        _slotAreaSceneLockDashLayout: null as any,
        _slotAreaSceneLockedBtnLayout: null as any,
        timerLabel: null,
        completionLabel: null,
        levelLabel: null,
        dragLayer: null,
        dragNodes: [],
        _boardCellPool: new NodePool(),
        _boardSlotBgPool: new NodePool(),
        _sceneInputRoot: null,
        panelWin: null,
        panelLose: null,
        panelTimeoutContinue: null,
        _gameplayInitSeq: 0,
        _postPlayableWarmupSeq: 0,
        _postPlayableWarmupInitSeq: 0,
        _postPlayableWarmupQueue: [],
        _postPlayableWarmupRunning: false,
        _postPlayableWarmupRunningTaskName: '',
        _gameplayResultPanelPrefabCache: new Map<string, any>(),
        _gameplayResultPanelPrefabLoadCallbacks: null,
        _gameplayResultPanelPrefabLoadSeq: 0,
        _endgameHintPrefab: null,
        _endgameHintPrefabLoading: false,
        _endgameHintPrefabCallbacks: [],
        _endgameHintNodes: [],
        _endgameHintPool: [],
        _endgameHintLoadWarned: false,
        _pinddSpineFxSkeletonData: null,
        _pinddSpineFxSkeletonDataLoading: false,
        _pinddSpineFxSkeletonDataCallbacks: [],
        _pinddSpineFxPool: new NodePool(),
        _activePinddSpineFxNodes: [],
        _pinddSpineFxActiveCount: 0,
        _pinddSpineFxLoadWarned: false,
        _pinddSpineFxPlayWarned: false,
        _freezeSpineFxSkeletonData: null,
        _freezeSpineFxSkeletonDataLoading: false,
        _freezeSpineFxSkeletonDataCallbacks: [],
        _freezeSpineFxNode: null,
        _freezeSpineFxSeq: 0,
        _freezeSpineFxLoadWarned: false,
        _freezeSpineFxPlayWarned: false,
        _goldCountLbl: null,
        _settlementGoldCountLbl: null,
        _shopGoldLbl: null,
        _goldShopOpening: false,
        _acquireResourcePanelPrefab: null,
        _acquireResourcePanelPrefabPreloading: false,
        _skillTexturesEnsuring: false,
        _panelOpenInFlight: new Set<string>(),
        _pendingWinGoldReward: 0,
        _pendingWinAdBonusReward: 0,
        _winAdRewardClaimed: false,
        _winBaseGoldFlyPlayed: false,
        _settlementNextTransitioning: false,
        _settlementRevealState: 'idle',
        _settlementRevealToken: 0,
        currentBlock: null,
        isSelected: false,
        timeRemain: 0,
        _dynamicCountdownEnabled: false,
        _dynamicCountdownLevelId: 0,
        _dynamicCountdownEntryMode: '',
        _dynamicCountdownBaseTimeLimit: 0,
        _dynamicCountdownTimeLimit: 0,
        _dynamicCountdownFactor: 1,
        _dynamicCountdownReason: 'disabled',
        _dynamicCountdownAssisted: false,
        _dynamicCountdownFinalFailureRecorded: false,
        _dynamicCountdownFinalFailureLevel: 0,
        _timerPauseRefs: 0,
        _timerLockedForProp: false,
        _freezeTimeLeft: 0,
        _freezeTimeTotal: 0,
        slotRowCount: 1,
        slotUnlockedRows: 1,
        initialSlotRowCount: 1,
        _lastPlacedCells: null,
        _flyingTargets: new Set<string>(),
        _placementInputLocked: false,
        _placementInputLockRefs: 0,
        _placementVisualRefs: 0,
        _placementAnimationGeneration: 0,
        _placementOperationWatchdogs: new Map<string, any>(),
        _flyingTargetRefs: new Map<string, number>(),
        _hiddenSlotIndexRefs: new Map<number, number>(),
        _hiddenBoardCells: new Set<string>(),
        _hiddenSlotIndices: new Set<number>(),
        _skillActive: false,
        _skillAnimOnly: false,
        _skillUsageGeneration: 0,
        _activeSkillUsageGeneration: 0,
        _skillUsageWatchdog: null as any,
        _skillUsageWatchdogMeta: null,
        _skillUsageWatchdogRecovery: null as any,
        _lastSkillWatchdogRecovery: null,
        _skillTimerPauseToken: '',
        _adShowing: false,
        _adTimerSuspended: false,
        _adRewardInitialTimeLimit: 0,
        _adRewardFreezeHintShown: false,
        _adRewardFreezeEntryClicked: false,
        _adRewardFreezeGlowNode: null,
        _slotAddReminderCount: 0,
        _slotAddReminderLastAt: 0,
        _slotAddReminderLastReason: '',
        _slotAddReminderFirstFullShown: false,
        _slotAddReminderHalfTimeShown: false,
        _timerStarted: false,
        cellSize: DEFAULT_CELL_SIZE,
        cellGap: DEFAULT_CELL_GAP,
        _completedColors: new Set<number>(),
        _pendingColorCompleteEffects: new Map<number, boolean>(),
        _patternCompleteWinPending: false,
        _patternCompleteMatchFxRoot: null,
        _pulseTweens: [] as Array<{ stop(): void }>,
        _selectedSlotIndices: [],
        _selectionOverlayNodes: [],
        _floatingCells: [],
        _floatingSlots: [],
        _wandMode: false,
        _wandRectNode: null,
        _wandDragStart: null,
        _wandRectStartPos: new Vec3(),
        _wandSparkleNodes: [],
        _vigorCountLbl: null as Label | null,
        _vigorTimeLbl: null as Label | null,
        _vigorTickDt: 0,
        _noLivesModal: null,
        _recoverVigorStatusLbl: null as Label | null,
        _recoverVigorVideoButton: null as Node | null,
        _recoverVigorShareButton: null as Node | null,
        _recoverVigorShareRemainingLbl: null as Label | null,
        _recoverVigorCloseButton: null as Node | null,
        _recoverVigorBusy: false,
        _recoverVigorTransactionSeq: 0,
        _recoverVigorTransaction: null as {
            id: number;
            source: string;
            method: string;
            startedAt: number;
        } | null,
        _guideMode: 'none',
        _activeGameplayGuideLayoutMode: 'none',
        _guideStep: -1,
        _guideTotalSteps: 0,
        _guidePhase: 'select',
        _guideFirstColorId: 0,
        _guideSecondColorId: 0,
        _guideLayer: null,
        _guideMask: null,
        _guideHand: null,
        _guideBubble: null,
        _guideBubbleLbl: null,
        _guidePromptDefaultLabelColor: null as Color | null,
        _guidePromptDefaultCenterY: null as number | null,
        _guideHandsRoot: null as Node | null,
        _guidePinchLeftHand: null as Node | null,
        _guidePinchRightHand: null as Node | null,
        _guideStatus: 'idle',
        _guidePreviewStep: -1,
        _guideRenderStep: -1,
        _guidePreviewVisible: false,
        _guideTargetFeedbackNode: null as Node | null,
        _guideDimMaskNode: null as Node | null,
        _guideDemoAssistNode: null as Node | null,
        _guideDemoPlayingUntil: 0,
        _guideTransientFeedbackNodes: [] as Node[],
        _guideVisualShownAt: 0,
        _guideActionEnabledAt: 0,
        _guideTransitionStartedAt: 0,
        _guideTransitionWatchdogToken: 0,
        _guideTransitionSlowHandler: null as (() => void) | null,
        _guideTransitionHardHandler: null as (() => void) | null,
        _guideWrongAttemptCount: 0,
        _guideReminderStage: 0,
        _guideReminderHandler: null as (() => void) | null,
        _guideReminderToken: 0,
        _guideReminderDueAt: 0,
        _guideReminderRemainingMs: 0,
        _guideReminderVisible: false,
        _guideSuppressInitialHandPulse: false,
        _guideReminderVoicePlayed: false,
        _smartIdleHintTimerHandler: null as (() => void) | null,
        _smartIdleHintToken: 0,
        _smartIdleHintActive: false,
        _smartIdleHintPlan: null as any,
        _smartIdleHintShownCount: 0,
        _smartIdleHintEpisodeCycle: 0,
        _smartIdleHintInputActive: false,
        _gameplayInvalidTapFeedbackToken: 0,
        _guideReminderPausedForLifecycle: false,
        _guideZoomStartScale: 1,
        _guideZoomLastScale: 1,
        _guideZoomAccumulatedScaleDelta: 0,
        _guideZoomLastSource: '',
        _guideLevel2SlotPlacementSucceeded: false,
        _guidePulseTweens: [] as Tween<Node>[],
        _guideHighlightCells: [],
        _guideInputSuspended: false,
        _modalFocusRefs: 0,
        _runtimeOwnerSeq: 0,
        _runtimeOwners: new Map<string, Map<string, string>>(),
        _runtimeOwnerMeta: new Map<string, any>(),
        _pendingTutorialInteractiveReadyStep: -1,
        _interactionTouchAttemptCount: 0,
        _lastGuideVoiceToken: '',
        _loadingOverlay: null,
        _loadingProgressFill: null,
        _loadingProgressLabel: null,
        _loadingProgressLabelShadow: null,
        _loadingProgressLabelTween: null,
        _loadingProgressGroup: null,
        _loadingProgressFillNode: null,
        _loadingProgressFullWidth: 0,
        _loadingProgressFullHeight: 0,
        _loadingProgressTrackWidth: 0,
        _loadingSlowActions: null,
        _loadingProgressIntroHandler: null as (() => void) | null,
        _loadingSlowActionHandler: null as (() => void) | null,
        _loadingWatchdogHandler: null as (() => void) | null,
        _loadingRouteActionInFlight: false,
        _loadingHasMeasuredProgress: false,
        _gameplayLoadRequestVersion: 0,
        _loadingProgressPercent: 0,
        _loadingOverlayVersion: 0,
        _loadingOwnerToken: '',
        _loadingShine: null,
        _loadingShineTween: null,
        _loadingProgress: 0,
        _loadingClosing: false,
        _startupCloudRestorePending: false,
        _startupCloudRestoreHadLocalUserState: false,
        _startupCloudSaveBlockedForSession: false,
        _startupCloudRestorePromise: null as Promise<any> | null,
        _startupCloudRestoreStatus: '' as string,
        _deferredCloudGameStateSync: false,
        _deferredLeaderboardProgress: 0,
        _remoteLoadErrorOverlay: null,
        _collectionOverlay: null,
        _backgroundSkinPanelPrefab: null,
        _backgroundSkinPanelPreloading: false,
        _collectionPage: 0,
        _collectionTotalPages: 0,
        _collectionLevelIds: [],
        _themeOverlay: null,
        _isThemeLevel: false,
        _currentThemeLevelId: 0,
        _collectionContentNode: null,
        _collectionScrollContentNode: null,
        _collectionPreviewItems: [],
        _collectionPreviewRowPitch: 0,
        _collectionPreviewBufferRows: 2,
        _collectionPageIndicator: null,
        _collectionScrollStartY: 0,
        _collectionScrollDragging: false,
        _collectionScrollMoved: false,
        _collectionScrollSuppressClick: false,
        _collectionScrollInertiaStep: null,
        _collectionImageModal: null,
        _themeImageModal: null,
        _pinchGuideLayer: null,
        _pinchGuideAutoCloseHandler: null,
        gestureMode: 'idle',
        suppressTap: false,
        activeBoardTouches: new Map<number, Vec2>(),
        pinchTouchIds: null,
        panStartPos: new Vec2(),
        panStartParentPos: new Vec2(),
        panStartGroupPos: new Vec3(),
        pinchStartDist: 0,
        pinchStartScale: 1,
        pinchAnchorBoardLocal: new Vec2(),
        totalMoveDistance: 0,
        boardViewScale: 1,
        boardHomeScale: 1,
        _friendRankTouchStartY: 0,
        _friendRankLastMoveAt: 0,
        _friendRankScrollOffset: 0,
        _friendRankScrollVelocity: 0,
        _friendRankInertiaStep: null,
        _friendRankLastScrollPostAt: 0,
        _friendRankPendingScrollOffset: 0,
        _friendRankScrollPostScheduled: false,
        _friendRankOpenDataActive: false,
        _friendRankAvatarCache: null,
        _friendRankAvatarCacheAt: 0,
        boardHomePos: new Vec3(0, 140, 0),
        _boardZoomControlUi: null,
        sfCache: new Map<string, SpriteFrame>(),
        _spriteFrameCacheMeta: new Map<string, any>(),
        _bootstrapAtlasFrameCache: new Map<string, SpriteFrame>(),
        bootstrapBundle: null as Bundle | null,
        gameAssetsBundle: null as Bundle | null,
        levelDataBundle: null as Bundle | null,
        _preloadingBundle: false,
        _levelDataBundleLoadingCallbacks: null,
        _levelDataLoadStopped: false,
        _bootstrapBundleLoadingCallbacks: null,
        _gameAssetsBundleLoadingCallbacks: null,
        _pendingSpriteFrameLoads: new Map<string, Array<(sf: SpriteFrame | null) => void>>(),
        _spriteFrameLoadQueue: [],
        _spriteFrameLoadInFlight: 0,
        _spriteFrameLoadQueueCancelled: false,
        _spriteFrameApplySeq: 0,
        _spriteFrameApplyPending: new Map<string, any>(),
        _spriteFrameApplyFlushScheduled: false,
        _bootstrapBeanAtlasReady: false,
        _bootstrapBeanAtlasLoadingCallbacks: null,
        _bootstrapBeanAtlasTexture: null,
        _bootstrapBeanAtlasImageAsset: null,
        _bootstrapBeanAtlasTextureReleaseMode: 'asset',
        _flyBeanPool: new NodePool(),
        _activeFlyBeanNodes: new Set<Node>(),
        _brightFlashPool: new NodePool(),
        _activeBrightFlashCount: 0,
        _currentExternalLevelFilePath: '',
        _currentExternalLevelId: 0,
        _currentExternalLevelPrefix: 'level_',
        _activeLogicalLevelId: 1,
        _activePhysicalLevelId: 1,
        _activeGameplayEntryMode: 'main',
        _activeSlotRowPolicy: null,
        _bootstrapOnlyGameplayStartup: false,
        _startupBootstrapPrefetchState: 'idle',
        _startupBootstrapPrefetchLevelId: 0,
        _startupBootstrapPrefetchCallbacks: null as Array<(ready: boolean) => void> | null,
        _startupBootstrapPrefetchReleaseQueued: false,
        _startupBackgroundServicesStarted: false,
        _startupBackgroundServicesUiReady: false,
        _startupBackgroundServicesRunStarted: false,
        _pendingStartupBackgroundServices: null as any,
        _pendingStartupCloudRestoredLevel: 0,
        _pendingStartupCloudRestoredToastText: '',
        _pendingStartupCloudRestoredHadLocalUserState: false,
        _currentLevelUnlimitedTime: false,
        _firstFunnelTouchSent: false,
        _firstFunnelSelectSent: false,
        _firstFunnelPlaceAttemptSent: false,
        _firstFunnelPlaceSuccessSent: false,
        _firstLevelReleaseDiagToken: 0,
        _firstLevelReleaseDiagStartedAt: 0,
        _firstLevelReleaseDiagEventCount: 0,
        _firstLevelReleaseCanvasTouchCount: 0,
        _firstLevelReleaseObserverNode: null as Node | null,
        _firstLevelReleaseObserverHandler: null as ((event: any) => void) | null,
        _firstLevelReleaseObserverBoundAt: 0,
        _firstLevelReleaseEarlyTouchCount: 0,
        _firstLevelReleaseEarlyFirstTouchAt: 0,
        _firstLevelReleaseEarlyLastTouchAt: 0,
        _firstLevelReleaseNativeTouchApi: null as any,
        _firstLevelReleaseNativeTouchHandler: null as ((event: any) => void) | null,
        _firstLevelReleaseNativeTouchObserverState: 'unavailable',
        _firstLevelReleaseNativeTouchBoundAt: 0,
        _firstLevelReleaseNativeTouchCount: 0,
        _firstLevelReleaseNativeEarlyTouchCount: 0,
        _firstLevelReleaseNativeEarlyFirstTouchAt: 0,
        _firstLevelReleaseNativeEarlyLastTouchAt: 0,
        _firstLevelTouchTraceSeq: 0,
        _firstLevelTouchTraceId: '',
        _firstLevelTouchTraceStartedAt: 0,
        _firstLevelTouchTraceUpdatedAt: 0,
        _firstLevelTouchTraceStages: [] as string[],
        _firstLevelReleaseAfterDrawHandler: null as (() => void) | null,
        _firstLevelReleaseAfterDrawFallbackTimer: null as any,
        _firstLevelReleaseAfterDrawSeen: false,
        _firstLevelReleaseDelayedHandlers: [] as Array<() => void>,
        _userStateLifecycleBound: false,
        _gameForeground: true,
        _pendingPostAdSkillAction: null,
        _pendingRewardedAdPreload: null,
        _rewardedAdWarmSlotDesired: false,
        _rewardedAdWarmSlotReason: '',
        _rewardedAdWarmSlotRetryCount: 0,
        _rewardedAdWarmSlotBlockedReason: '',
        _rewardedAdWarmSlotLastEnsureAt: 0,
        _rewardedAdPendingStrip: null,
        _rewardedAdStateUnsubscribe: null as (() => void) | null,
        _rewardedAdTelemetryPage: '',
        _rewardedAdTelemetryLevelId: 0,
        _rewardedGrantTransactionSeq: 0,
        _rewardedGrantTransaction: null,
        _rewardedGrantTimedOutClaims: new Set<string>(),
        mainMenuNode: null,
        _homeGameplayWarmupKey: '',
        _homeGameplayWarmupState: 'idle',
        _themeGroupsCache: null,
        _themeGroupsLoading: false,
        _themePreviewItems: [],
        _themePreviewRowPitch: 0,
        _themePreviewBufferRows: 1,
        _backgroundSkinConfigCache: null,
        _backgroundSkinConfigLoadingCallbacks: null,
        _skinBundleCache: new Map<string, Bundle>(),
        _skinBundleLoadingCallbacks: new Map<string, Array<(bundle: Bundle | null, err?: Error | null) => void>>(),
        _backgroundSkinFrameCache: new Map<number, SpriteFrame>(),
        _backgroundSkinIconCache: new Map<number, SpriteFrame>(),
        _backgroundSkinFrameCacheMeta: new Map<number, any>(),
        _backgroundSkinIconCacheMeta: new Map<number, any>(),
        _skinSpriteFrameLoadingCallbacks: new Map<string, Array<(sf: SpriteFrame | null, err?: Error | null) => void>>(),
        _backgroundSkinIconLoadQueue: [],
        _backgroundSkinIconLoadInFlight: 0,
        _backgroundSkinIconLoadSeq: 0,
        _backgroundSkinPanelVirtualState: null,
        _equippedBackgroundSkinId: 0,
        _equippedBackgroundSkinFrame: null as SpriteFrame | null,
        _appliedGameplayBackgroundSkinId: 0,
        _appliedGameplayBackgroundRefreshSeq: -1,
        _gameplayBackgroundSkinRetryToken: 0,
        _backgroundSkinPanelOverlay: null,
        _backgroundSkinAdUnlocking: false,
    });

    runtime.boardViewport = new BoardViewportController({
        minScale: runtime.constructor.MIN_SCALE,
        maxScale: runtime.constructor.MAX_SCALE,
        fallbackWidth: runtime.constructor.VIEWPORT_WIDTH,
        fallbackHeight: runtime.constructor.VIEWPORT_HEIGHT,
        getBoardGroup: () => runtime.boardGroup,
        getBoardNode: () => runtime.boardNode,
        getSafeViewportRect: () => runtime.getBoardSafeViewportRect(),
    });
}
