import {
    BoardViewportController,
    Bundle,
    DEFAULT_CELL_GAP,
    DEFAULT_CELL_SIZE,
    Label,
    Node,
    NodePool,
    SpriteFrame,
    Tween,
    Vec2,
    Vec3,
} from './GameCtrlShared';

export function initializeGameCtrlState(runtime: any): void {
    if (runtime._runtimeStateInitialized) {
        return;
    }
    runtime._runtimeStateInitialized = true;

    Object.assign(runtime, {
        isGameEnd: false,
        boardModel: null,
        slotModel: null,
        levelData: null,
        boardNode: null,
        boardSlotsNode: null,
        _boardSlotBatchRenderer: null,
        _boardSlotBatchRenderers: [],
        boardSlotBgNodes: [],
        boardGroup: null,
        cellNodes: [],
        slotNodes: [],
        slotMarkerNodes: [],
        slotAreaNode: null,
        _slotAreaSceneBaseX: 0,
        _slotAreaSceneBasePanelBottomY: null as number | null,
        _slotAreaScenePanelLocalY: 0,
        _slotAreaScenePanelWidth: 0,
        _slotAreaSceneRowSpacing: null as number | null,
        _slotAreaSceneLockMaskLayout: null as any,
        _slotAreaSceneLockDashLayout: null as any,
        _slotAreaSceneLockedBtnLayout: null as any,
        timerLabel: null,
        completionLabel: null,
        levelLabel: null,
        dragLayer: null,
        dragNodes: [],
        _boardCellPool: new NodePool(),
        _boardSlotBgPool: new NodePool(),
        _sceneInputRoot: null,
        panelWin: null,
        panelLose: null,
        panelTimeoutContinue: null,
        _gameplayInitSeq: 0,
        _gameplayResultPanelPrefabCache: new Map<string, any>(),
        _gameplayResultPanelPrefabLoadCallbacks: null,
        _gameplayResultPanelPrefabLoadSeq: 0,
        _endgameHintPrefab: null,
        _endgameHintPrefabLoading: false,
        _endgameHintPrefabCallbacks: [],
        _endgameHintNodes: [],
        _endgameHintPool: [],
        _endgameHintLoadWarned: false,
        _colorCompleteMatchFxPrefab: null,
        _colorCompleteMatchFxPrefabLoading: false,
        _colorCompleteMatchFxPrefabCallbacks: [],
        _colorCompleteMatchFxPool: [],
        _colorCompleteMatchFxLoadWarned: false,
        _goldCountLbl: null,
        _shopGoldLbl: null,
        _goldShopOpening: false,
        _skillTexturesEnsuring: false,
        _panelOpenInFlight: new Set<string>(),
        _pendingWinGoldReward: 0,
        _pendingWinAdBonusReward: 0,
        _winAdRewardClaimed: false,
        _settlementNextTransitioning: false,
        currentBlock: null,
        isSelected: false,
        timeRemain: 0,
        _dynamicCountdownEnabled: false,
        _dynamicCountdownLevelId: 0,
        _dynamicCountdownEntryMode: '',
        _dynamicCountdownBaseTimeLimit: 0,
        _dynamicCountdownTimeLimit: 0,
        _dynamicCountdownFactor: 1,
        _dynamicCountdownReason: 'disabled',
        _dynamicCountdownAssisted: false,
        _dynamicCountdownFinalFailureRecorded: false,
        _dynamicCountdownFinalFailureLevel: 0,
        _timerPauseRefs: 0,
        _timerLockedForProp: false,
        slotRowCount: 1,
        slotUnlockedRows: 1,
        initialSlotRowCount: 1,
        _lastPlacedCells: null,
        _flyingTargets: new Set<string>(),
        _hiddenBoardCells: new Set<string>(),
        _hiddenSlotIndices: new Set<number>(),
        _skillActive: false,
        _skillAnimOnly: false,
        _adShowing: false,
        _adTimerSuspended: false,
        _timerStarted: false,
        cellSize: DEFAULT_CELL_SIZE,
        cellGap: DEFAULT_CELL_GAP,
        _completedColors: new Set<number>(),
        _pulseTweens: [] as Array<{ stop(): void }>,
        _selectedSlotIndices: [],
        _selectionOverlayNodes: [],
        _floatingCells: [],
        _floatingSlots: [],
        _wandMode: false,
        _wandRectNode: null,
        _wandDragStart: null,
        _wandRectStartPos: new Vec3(),
        _wandSparkleNodes: [],
        _vigorCountLbl: null as Label | null,
        _vigorTimeLbl: null as Label | null,
        _vigorTickDt: 0,
        _noLivesModal: null,
        _guideMode: 'none',
        _guideStep: -1,
        _guideTotalSteps: 0,
        _guidePhase: 'select',
        _guideFirstColorId: 0,
        _guideSecondColorId: 0,
        _guideLayer: null,
        _guideMask: null,
        _guideHand: null,
        _guideBubble: null,
        _guideBubbleLbl: null,
        _guidePulseTweens: [] as Tween<Node>[],
        _guideHighlightCells: [],
        _guideInputSuspended: false,
        _modalFocusRefs: 0,
        _lastGuideVoiceToken: '',
        _loadingOverlay: null,
        _loadingProgressFill: null,
        _loadingProgressLabel: null,
        _loadingProgressLabelShadow: null,
        _loadingProgressLabelTween: null,
        _loadingProgressPercent: 0,
        _loadingOverlayVersion: 0,
        _loadingShine: null,
        _loadingShineTween: null,
        _loadingProgress: 0,
        _loadingClosing: false,
        _startupCloudRestorePending: false,
        _startupCloudRestoreHadLocalUserState: false,
        _startupCloudSaveBlockedForSession: false,
        _startupCloudRestorePromise: null as Promise<any> | null,
        _startupCloudRestoreStatus: '' as string,
        _deferredCloudGameStateSync: false,
        _deferredLeaderboardProgress: 0,
        _remoteLoadErrorOverlay: null,
        _collectionOverlay: null,
        _collectionPage: 0,
        _collectionTotalPages: 0,
        _collectionLevelIds: [],
        _themeOverlay: null,
        _isThemeLevel: false,
        _currentThemeLevelId: 0,
        _collectionContentNode: null,
        _collectionScrollContentNode: null,
        _collectionPreviewItems: [],
        _collectionPreviewRowPitch: 0,
        _collectionPreviewBufferRows: 2,
        _collectionPageIndicator: null,
        _collectionScrollStartY: 0,
        _collectionScrollDragging: false,
        _collectionScrollMoved: false,
        _collectionScrollSuppressClick: false,
        _collectionScrollInertiaStep: null,
        _collectionImageModal: null,
        _themeImageModal: null,
        _pinchGuideLayer: null,
        gestureMode: 'idle',
        suppressTap: false,
        activeBoardTouches: new Map<number, Vec2>(),
        pinchTouchIds: null,
        panStartPos: new Vec2(),
        panStartParentPos: new Vec2(),
        panStartGroupPos: new Vec3(),
        pinchStartDist: 0,
        pinchStartScale: 1,
        pinchAnchorBoardLocal: new Vec2(),
        totalMoveDistance: 0,
        boardViewScale: 1,
        boardHomeScale: 1,
        _friendRankTouchStartY: 0,
        _friendRankLastMoveAt: 0,
        _friendRankScrollOffset: 0,
        _friendRankScrollVelocity: 0,
        _friendRankInertiaStep: null,
        _friendRankLastScrollPostAt: 0,
        _friendRankPendingScrollOffset: 0,
        _friendRankScrollPostScheduled: false,
        _friendRankAvatarCache: null,
        _friendRankAvatarCacheAt: 0,
        boardHomePos: new Vec3(0, 140, 0),
        _boardZoomControlUi: null,
        sfCache: new Map<string, SpriteFrame>(),
        _spriteFrameCacheMeta: new Map<string, any>(),
        _bootstrapAtlasFrameCache: new Map<string, SpriteFrame>(),
        bootstrapBundle: null as Bundle | null,
        gameAssetsBundle: null as Bundle | null,
        levelDataBundle: null as Bundle | null,
        _preloadingBundle: false,
        _levelDataBundleLoadingCallbacks: null,
        _levelDataLoadStopped: false,
        _bootstrapBundleLoadingCallbacks: null,
        _gameAssetsBundleLoadingCallbacks: null,
        _pendingSpriteFrameLoads: new Map<string, Array<(sf: SpriteFrame | null) => void>>(),
        _spriteFrameLoadQueue: [],
        _spriteFrameLoadInFlight: 0,
        _bootstrapBeanAtlasReady: false,
        _bootstrapBeanAtlasLoadingCallbacks: null,
        _bootstrapBeanAtlasTexture: null,
        _bootstrapBeanAtlasImageAsset: null,
        _bootstrapBeanAtlasTextureReleaseMode: 'asset',
        _effectsAtlasReady: false,
        _effectsAtlasLoadingCallbacks: null,
        _flyBeanPool: new NodePool(),
        _frameFxPool: new NodePool(),
        _brightFlashPool: new NodePool(),
        _effectFrameCache: new Map<string, SpriteFrame[]>(),
        _activeFrameFxCount: 0,
        _activeBrightFlashCount: 0,
        _currentExternalLevelFilePath: '',
        _currentExternalLevelId: 0,
        _currentExternalLevelPrefix: 'level_',
        _firstLevelRouteBucket: 'bucket_a',
        _activeLogicalLevelId: 1,
        _activePhysicalLevelId: 1,
        _activeGameplayEntryMode: 'main',
        _activeSlotRowPolicy: null,
        _bootstrapOnlyGameplayStartup: false,
        _startupBootstrapPrefetchState: 'idle',
        _startupBootstrapPrefetchLevelId: 0,
        _startupBootstrapPrefetchCallbacks: null as Array<(ready: boolean) => void> | null,
        _startupBootstrapPrefetchReleaseQueued: false,
        _startupBackgroundServicesStarted: false,
        _currentLevelUnlimitedTime: false,
        _firstFunnelTouchSent: false,
        _firstFunnelSelectSent: false,
        _firstFunnelPlaceAttemptSent: false,
        _firstFunnelPlaceSuccessSent: false,
        _userStateLifecycleBound: false,
        _gameForeground: true,
        _pendingPostAdSkillAction: null,
        _pendingRewardedAdPreload: null,
        mainMenuNode: null,
        _homeGameplayWarmupKey: '',
        _homeGameplayWarmupState: 'idle',
        _themeGroupsCache: null,
        _themeGroupsLoading: false,
        _backgroundSkinConfigCache: null,
        _backgroundSkinConfigLoadingCallbacks: null,
        _skinBundleCache: new Map<string, Bundle>(),
        _skinBundleLoadingCallbacks: new Map<string, Array<(bundle: Bundle | null, err?: Error | null) => void>>(),
        _backgroundSkinFrameCache: new Map<number, SpriteFrame>(),
        _backgroundSkinIconCache: new Map<number, SpriteFrame>(),
        _skinSpriteFrameLoadingCallbacks: new Map<string, Array<(sf: SpriteFrame | null, err?: Error | null) => void>>(),
        _equippedBackgroundSkinId: 0,
        _equippedBackgroundSkinFrame: null as SpriteFrame | null,
        _backgroundSkinPanelOverlay: null,
    });

    runtime.boardViewport = new BoardViewportController({
        minScale: runtime.constructor.MIN_SCALE,
        maxScale: runtime.constructor.MAX_SCALE,
        fallbackWidth: runtime.constructor.VIEWPORT_WIDTH,
        fallbackHeight: runtime.constructor.VIEWPORT_HEIGHT,
        getBoardGroup: () => runtime.boardGroup,
        getBoardNode: () => runtime.boardNode,
        getSafeViewportRect: () => runtime.getBoardSafeViewportRect(),
    });
}
