import { installAssetBootstrapModule } from './GameCtrlModules/AssetBootstrapModule';
import { installSkinBackgroundModule } from './GameCtrlModules/SkinBackgroundModule';
import { installBoardInputViewportModule } from './GameCtrlModules/BoardInputViewportModule';
import { installBoardZoomControlModule } from './GameCtrlModules/BoardZoomControlModule';
import { installGameplayLevelFlowModule } from './GameCtrlModules/GameplayLevelFlowModule';
import { installGameplayPlacementFxModule } from './GameCtrlModules/GameplayPlacementFxModule';
import { installGameplayFreezeEffectModule } from './GameCtrlModules/GameplayFreezeEffectModule';
import { installGameplaySkillMagnetModule } from './GameCtrlModules/GameplaySkillMagnetModule';
import { installFirstLevelRouteModule } from './GameCtrlModules/FirstLevelRouteModule';
import { installHomeCommerceModule } from './GameCtrlModules/HomeCommerceModule';
import { installHomeAdFlowModule } from './GameCtrlModules/HomeAdFlowModule';
import { installSceneHomeEntryModule } from './GameCtrlModules/SceneHomeEntryModule';
import { installFriendRankModule } from './GameCtrlModules/FriendRankModule';
import { installGameplaySlotSkillModule } from './GameCtrlModules/GameplaySlotSkillModule';
import { installGameplaySkillWandModule } from './GameCtrlModules/GameplaySkillWandModule';
import { installGameplayAdRewardHintModule } from './GameCtrlModules/GameplayAdRewardHintModule';
import { installPlayerMetaStateModule } from './GameCtrlModules/PlayerMetaStateModule';
import { installGuideLeaderboardModule } from './GameCtrlModules/GuideLeaderboardModule';
import { installSettlementHudModule } from './GameCtrlModules/SettlementHudModule';
import { installCollectionAvatarModule } from './GameCtrlModules/CollectionAvatarModule';
import { installThemePanelFlowModule } from './GameCtrlModules/ThemePanelFlowModule';
import { installThemeLoadingOverlayModule } from './GameCtrlModules/ThemeLoadingOverlayModule';
import { installCollectionGuideModule } from './GameCtrlModules/CollectionGuideModule';
import { installGameplayShareLoadingModule } from './GameCtrlModules/GameplayShareLoadingModule';
import { installSettingsPanelModule } from './GameCtrlModules/SettingsPanelModule';
import { installTutorialGuideModule } from './GameCtrlModules/TutorialGuideModule';
import { installEndgameHintModule } from './GameCtrlModules/EndgameHintModule';
import { installDynamicCountdownDdaModule } from './GameCtrlModules/DynamicCountdownDdaModule';
import { installPostPlayableWarmupModule } from './GameCtrlModules/PostPlayableWarmupModule';
import { installTopHudModule } from './GameCtrlModules/TopHudModule';

export function installGameCtrlModules(runtime: any): void {
    if (runtime._gameCtrlModulesInstalled) {
        return;
    }
    runtime._gameCtrlModulesInstalled = true;
    installPlayerMetaStateModule(runtime);
    installFirstLevelRouteModule(runtime);
    installAssetBootstrapModule(runtime);
    installTopHudModule(runtime);
    installSkinBackgroundModule(runtime);
    installDynamicCountdownDdaModule(runtime);
    installHomeAdFlowModule(runtime);
    installHomeCommerceModule(runtime);
    installSceneHomeEntryModule(runtime);
    installGameplayLevelFlowModule(runtime);
    installGameplaySlotSkillModule(runtime);
    installGameplayFreezeEffectModule(runtime);
    installGameplaySkillWandModule(runtime);
    installGameplaySkillMagnetModule(runtime);
    installGameplayAdRewardHintModule(runtime);
    installBoardInputViewportModule(runtime);
    installBoardZoomControlModule(runtime);
    installGameplayPlacementFxModule(runtime);
    installEndgameHintModule(runtime);
    installSettlementHudModule(runtime);
    installTutorialGuideModule(runtime);
    installGuideLeaderboardModule(runtime);
    installFriendRankModule(runtime);
    installCollectionAvatarModule(runtime);
    installThemePanelFlowModule(runtime);
    installThemeLoadingOverlayModule(runtime);
    installCollectionGuideModule(runtime);
    installGameplayShareLoadingModule(runtime);
    installSettingsPanelModule(runtime);
    installPostPlayableWarmupModule(runtime);
}
