export const LOGICAL_COCOS_CORE_BUNDLE_NAME = 'cocosCore';
export const LOGICAL_FIRST_PLAY_BUNDLE_NAME = 'firstPlay';
export const LOGICAL_HOME_BUNDLE_NAME = 'home';
export const LOGICAL_GAMEPLAY_BUNDLE_NAME = 'gameplay';
export const LOGICAL_REMOTE_LEVEL_DATA_BUNDLE_NAME = 'remoteLevelData';

export const PHYSICAL_COCOS_CORE_BUNDLE_NAME = 'main';
export const PHYSICAL_FIRST_PLAY_BUNDLE_NAME = 'bootstrap';
export const PHYSICAL_HOME_BUNDLE_NAME = 'homeAssets';
export const PHYSICAL_GAMEPLAY_BUNDLE_NAME = 'gameAssets';
export const PHYSICAL_REMOTE_LEVEL_DATA_BUNDLE_NAME = 'levelData';

export const LOCAL_BOOTSTRAP_BUNDLE_NAME = PHYSICAL_FIRST_PLAY_BUNDLE_NAME;
export const HOME_ASSETS_BUNDLE_NAME = PHYSICAL_HOME_BUNDLE_NAME;
export const GAME_ASSETS_BUNDLE_NAME = PHYSICAL_GAMEPLAY_BUNDLE_NAME;
export const LEVEL_DATA_BUNDLE_NAME = PHYSICAL_REMOTE_LEVEL_DATA_BUNDLE_NAME;
